import { Header } from './components/Header';
import './globals.css';
import { myFont } from './font';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Nestor Felipe</title>
      </head>
      <body className={myFont.variable}>
      {/* <body> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
